server:
  port: 8080

logging:
  level:
    root: debug

spring:
  main:
    banner-mode: console

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_SECRET_ID}