spring:
  profiles:
    active: local

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_SECRET_ID}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile

  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expire-period: 900000  # 15분
  refresh-token:
    expire-period: 604800000  # 7일
  type: Bearer

cron:
  github:
    fetch-interval: 0 */10 * ? * *
    fetch-days: 1
  velog:
    fetch-interval: 0 */30 * ? * *
    fetch-days: 1
