spring:
  profiles:
    active: local

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_SECRET_ID}

jwt:
  secret: ${JWT_SECRET}
  access-token:
    subject: accessToken
    expire-period: 900000  # 15분
  refresh-token:
    subject: refreshToken
    expire-period: 604800000  # 7일
