spring:
  main:
    banner-mode: off
  config:
    activate:
      on-profile: local
    import: classpath:config/local-config.properties
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:db/data.sql
      mode: always
server:
  address: 127.0.0.1